/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106691-g43afd8c681-20220427"
#endif /* AVUTIL_FFVERSION_H */
